name: Trigger PythonAnywhere Task

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
 
jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Richiama endpoint PythonAnywhere
        run: |
          curl -X GET "https://rmadaudo.pythonanywhere.com/ryanair_price"
